function [para1, para2, para3, para4, para5, filePath] = NCDialog_v2

% 1. biasing Pulse의 sign
% 2. capacitor area
% 3. Qres tolerance percentage


filePath = matlab.desktop.editor.getActiveFilename;
% fileFolder = filePath(1:find(filePath == '/' ,1, 'last')-1);
lastSlash = find(filePath == filesep, 1, 'last');
fileFolder = filePath(1:lastSlash - 1);
filePath = fullfile(fileFolder, 'NCDialogPara.mat');
% disp(fileFolder)

% filePath = strcat(fileFolder , "\NCDialogPara.mat");
fileDefault = dir(fullfile(fileFolder,'NCDialogPara.mat'));

if isempty(fileDefault) == 1
    NCDialogPara.BiasSign = 'Positive biased';
    NCDialogPara.CapacitorArea = '10000';      % 단위 : [um2]
    NCDialogPara.QresTolerance = '4';          % 단위 : [%]
    NCDialogPara.PulseWidth = '500';           % 단위 : [ns]
    NCDialogPara.PulseRiseFall = '20';         % 단위 : [ns] 
    save(filePath, "NCDialogPara")
else
    load(filePath);

end



Inch_SS = get(0,'screensize');

dialogSize = [0.45*Inch_SS(3) 0.3*Inch_SS(4) 230 520];
d = dialog('Position',dialogSize,'Name','Parameter Settings');


question_Title = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0 0.76*dialogSize(4) dialogSize(3) 0.2*dialogSize(4)],...
    'String', 'Condition Settings',...
    'FontSize',14, 'FontWeight', 'Bold','ForegroundColor','Red');

question_PulseInfo = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0 0.67*dialogSize(4) dialogSize(3) 0.2*dialogSize(4)],...
    'String', 'Pulse info [ns]',...
    'FontSize',12, 'FontWeight', 'Bold');

question_width = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0.2*dialogSize(3) 0.55*dialogSize(4) 0.3*dialogSize(3) 0.2*dialogSize(4)],...
    'String', 'Width [ns]',...
    'FontSize',8, 'FontWeight', 'Bold');

question_RiseFall = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0.55*dialogSize(3) 0.55*dialogSize(4) 0.3*dialogSize(3) 0.2*dialogSize(4)],...
    'String', 'Rise/Fall [ns]',...
    'FontSize',8, 'FontWeight', 'Bold');

question_PulseBias = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0 0.5*dialogSize(4) dialogSize(3) 0.2*dialogSize(4)],...
    'String', 'Pulse Bias Sign',...
    'FontSize',12, 'FontWeight', 'Bold');

question_CapArea = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0 0.34*dialogSize(4) dialogSize(3) 0.2*dialogSize(4)],...
    'String', 'Capacitor Area',...
    'FontSize',12, 'FontWeight', 'Bold');


question_QresTolerence = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0 0.17*dialogSize(4) dialogSize(3) 0.2*dialogSize(4)],...
    'String','Qres tolerence',...
    'FontSize',12, 'FontWeight', 'Bold');

get_text_PulseWidth = uicontrol('Parent',d,... 
    'Style','edit',...
    'Position',[0.22*dialogSize(3) 0.75*dialogSize(4) 0.25*dialogSize(3) 0.06*dialogSize(4)],...
    'String', NCDialogPara.PulseWidth,'FontSize',11,...
    'Callback',@get_text_PulseWidth_callback);

get_text_PulseRiseFall = uicontrol('Parent',d,... 
    'Style','edit',...
    'Position',[0.57*dialogSize(3) 0.75*dialogSize(4) 0.25*dialogSize(3) 0.06*dialogSize(4)],...
    'String', NCDialogPara.PulseRiseFall,'FontSize',11,...
    'Callback',@get_text_PulseRiseFall_callback);

if strcmp(NCDialogPara.BiasSign, 'Positive biased')==1
    popup = uicontrol('Parent',d,...
        'Style','popup',...
        'Position',[0.2*dialogSize(3) 0.39*dialogSize(4) 0.58*dialogSize(3) 0.25*dialogSize(4)],...
        'String',{'Positive biased','Negative biased'},'FontSize',11,...
        'Callback',@popup_callback);
else
    popup = uicontrol('Parent',d,...
        'Style','popup',...
        'Position',[0.2*dialogSize(3) 0.39*dialogSize(4) 0.58*dialogSize(3) 0.25*dialogSize(4)],...
        'String',{'Negative biased','Positive biased'},'FontSize',11,...
        'Callback',@popup_callback);
end


get_text_CapArea = uicontrol('Parent',d,...  
    'Style','edit',...
    'Position',[0.2*dialogSize(3) 0.42*dialogSize(4) 0.4*dialogSize(3) 0.06*dialogSize(4)],...
    'String', NCDialogPara.CapacitorArea,'FontSize',11,...
    'Callback',@get_text_CapArea_callback);

get_text_tolerence = uicontrol('Parent',d,... 
    'Style','edit',...
    'Position',[0.35*dialogSize(3) 0.25*dialogSize(4) 0.2*dialogSize(3) 0.06*dialogSize(4)],...
    'String', NCDialogPara.QresTolerance,'FontSize',11,...
    'Callback',@get_text_tolerence_callback);


question_CapAreaUnit = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0.6*dialogSize(3) 0.42*dialogSize(4) 0.2*dialogSize(3) 0.06*dialogSize(4)],...
    'String', 'um2',...
    'FontSize',11, 'FontWeight', 'Bold','ForegroundColor','Blue');

question_tolerenceUnit = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[0.55*dialogSize(3) 0.24*dialogSize(4) 0.1*dialogSize(3) 0.06*dialogSize(4)],...
    'String', '%',...
    'FontSize',11, 'FontWeight', 'Bold','ForegroundColor','Blue');


btn = uicontrol('Parent',d,...
    'Position',[0.05*dialogSize(3) 0.03*dialogSize(4) 0.9*dialogSize(3) 0.18*dialogSize(4)],...
    'String','Save & Continue','FontSize',13,'ForegroundColor','Blue',...
    'Callback','delete(gcf)');


para1 = NCDialogPara.BiasSign;
para2 = NCDialogPara.CapacitorArea;
para3 = NCDialogPara.QresTolerance;
para4 = NCDialogPara.PulseWidth;
para5 = NCDialogPara.PulseRiseFall;

% Wait for d to close before running to completion
uiwait(d);



    function popup_callback(popup,event)
        idx = popup.Value;
        popup_items = popup.String;
        para1 = char(popup_items(idx,:));
    end

    function  get_text_CapArea_callback(get_text_CapArea, event_12)
        %search_ext_idx = get_file_ext.Value;
        para2 = get_text_CapArea.String;     %y축 I(min) 값
    end

    function  get_text_tolerence_callback(get_text_tolerence, event_12)
        %search_ext_idx = get_file_ext.Value;
        para3 = get_text_tolerence.String;     %y축 I(min) 값
    end

    function  get_text_PulseWidth_callback(get_text_PulseWidth, event_12)
        %search_ext_idx = get_file_ext.Value;
        para4 = get_text_PulseWidth.String;     %y축 I(min) 값
    end

    function  get_text_PulseRiseFall_callback(get_text_PulseRiseFall, event_12)
        %search_ext_idx = get_file_ext.Value;
        para5 = get_text_PulseRiseFall.String;     %y축 I(min) 값
    end

save(filePath, "NCDialogPara")

end
